# Generated by Django 4.1.2 on 2022-10-27 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="year_of_release",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
